## Observations and Insights

In [17]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

# Study data files
mouse_metadata_path = "data/Mouse_metadata.csv"
study_results_path = "data/Study_results.csv"

# Read the mouse data and the study results
mouse_metadata = pd.read_csv(mouse_metadata_path)
study_results = pd.read_csv(study_results_path)

# Combine the data into a single dataset
merged_df = study_results.merge(mouse_metadata, on = 'Mouse ID')

# Display the data table for preview
merged_df.head(25)

,Mouse ID,Timepoint,Tumor Volume (mm3),Metastatic Sites,Drug Regimen,Sex,Age_months,Weight (g)
0,b128,0,45.000000,0,Capomulin,Female,9,22
1,b128,5,45.651331,0,Capomulin,Female,9,22
2,b128,10,43.270852,0,Capomulin,Female,9,22
3,b128,15,43.784893,0,Capomulin,Female,9,22
4,b128,20,42.731552,0,Capomulin,Female,9,22
5,b128,25,43.262145,1,Capomulin,Female,9,22
6,b128,30,40.605335,1,Capomulin,Female,9,22
7,b128,35,37.967644,1,Capomulin,Female,9,22
8,b128,40,38.379726,2,Capomulin,Female,9,22
9,b128,45,38.982878,2,Capomulin,Female,9,22
10,f932,0,45.000000,0,Ketapril,Male,15,29
11,g107,0,45.000000,0,Ketapril,Female,2,29
12,g107,5,48.791665,0,Ketapril,Female,2,29
13,g107,10,53.435987,0,Ketapril,Female,2,29
14,g107,15,58.135545,0,Ketapril,Female,2,29
15,g107,20,62.706031,0,Ketapril,Female,2,29
16,g107,25,64.663626,0,Ketapril,Female,2,29
17,g107,30,69.160520,0,Ketapril,Female,2,29
18,g107,35,71.905117,0,Ketapril,Female,2,29
19,a457,0,45.000000,0,Ketapril,Female,11,30
20,a457,5,47.462891,0,Ketapril,Female,11,30
21,a457,10,49.783419,0,Ketapril,Female,11,30
22,c819,0,45.000000,0,Ketapril,Male,21,25
23,c819,5,45.769249,1,Ketapril,Male,21,25
24,c819,10,46.658395,1,Ketapril,Male,21,25

In [20]:
# Checking the number of mice.
mice_num = merged_df['Mouse ID'].count()
print(mice_num)

1893

In [16]:
# Getting the duplicate mice by ID number that shows up for Mouse ID and Timepoint 
clean_merged_df = merged_df[['Mouse ID','Timepoint']].drop_duplicates()
clean_merged_df.head(25)

   Mouse ID  Timepoint
0      b128          0
1      b128          5
2      b128         10
3      b128         15
4      b128         20
5      b128         25
6      b128         30
7      b128         35
8      b128         40
9      b128         45
10     f932          0
11     g107          0
12     g107          5
13     g107         10
14     g107         15
15     g107         20
16     g107         25
17     g107         30
18     g107         35
19     a457          0
20     a457          5
21     a457         10
22     c819          0
23     c819          5
24     c819         10
25     c819         15
26     c819         20
27     c819         25
28     c819         30
29     c819         35
30     c819         40
31     h246          0
32     h246          5
33     h246         10
34     h246         15
35     h246         20
36     h246         25
37     h246         30
38     h246         35
39     h246         40
40     h246         45
41     p189          0
42     p189          5
43     p189         10
44     p189         15
45     p189         20
46     p189         25
47     p189         30
48     p189         35
49     p189         40

In [4]:
# Optional: Get all the data for the duplicate mouse ID.

In [5]:
# Create a clean DataFrame by dropping the duplicate mouse by its ID.

In [6]:
# Checking the number of mice in the clean DataFrame.

## Summary Statistics

In [7]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumor volume for each regimen

# Use groupby and summary statistical methods to calculate the following properties of each drug regimen: 
# mean, median, variance, standard deviation, and SEM of the tumor volume. 
# Assemble the resulting series into a single summary dataframe.

In [8]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumor volume for each regimen

# Using the aggregation method, produce the same summary statistics in a single line

## Bar and Pie Charts

In [9]:
# Generate a bar plot showing the total number of unique mice tested on each drug regimen using pandas.

In [10]:
# Generate a bar plot showing the total number of unique mice tested on each drug regimen using pyplot.

In [11]:
# Generate a pie plot showing the distribution of female versus male mice using pandas

In [12]:
# Generate a pie plot showing the distribution of female versus male mice using pyplot

## Quartiles, Outliers and Boxplots

In [13]:
# Calculate the final tumor volume of each mouse across four of the treatment regimens:  
# Capomulin, Ramicane, Infubinol, and Ceftamin

# Start by getting the last (greatest) timepoint for each mouse


# Merge this group df with the original dataframe to get the tumor volume at the last timepoint

In [14]:
# Put treatments into a list for for loop (and later for plot labels)


# Create empty list to fill with tumor vol data (for plotting)


# Calculate the IQR and quantitatively determine if there are any potential outliers. 

    
    # Locate the rows which contain mice on each drug and get the tumor volumes
    
    
    # add subset 
    
    
    # Determine outliers using upper and lower bounds

In [15]:
# Generate a box plot of the final tumor volume of each mouse across four regimens of interest

## Line and Scatter Plots

In [16]:
# Generate a line plot of tumor volume vs. time point for a mouse treated with Capomulin

In [17]:
# Generate a scatter plot of average tumor volume vs. mouse weight for the Capomulin regimen

## Correlation and Regression

In [18]:
# Calculate the correlation coefficient and linear regression model 
# for mouse weight and average tumor volume for the Capomulin regimen